"""Workflow Core Calculus package for internal lowering routes."""

from .model import (
    WCC_M1_ROUTE_SCHEMA_VERSION,
    WCC_M2_ROUTE_SCHEMA_VERSION,
    WCC_M3_ROUTE_SCHEMA_VERSION,
    WCC_M4_ROUTE_SCHEMA_VERSION,
    WccAtom,
    WccBindingValue,
    WccBody,
    WccCase,
    WccCaseArm,
    WccCall,
    WccFieldAccessAtom,
    WccHalt,
    WccIdentityFactory,
    WccInject,
    WccJoin,
    WccJoinParam,
    WccJump,
    WccLet,
    WccLiteralAtom,
    WccLoopContinue,
    WccLoopDone,
    WccLoopRole,
    WccNameAtom,
    WccNodeMetadata,
    WccOpaqueFrontendValue,
    WccPhaseTargetAtom,
    WccPhaseScope,
    WccPerform,
    WccProgram,
    WccRecJoin,
    WccRecordAtom,
    WccValue,
)
from .analysis import WccArmScope, WccJoinSite, WccLoopSite, WccScopeAnalysis, analyze_wcc_body
from .anf import normalize_wcc_body_to_anf
from .elaborate import elaborate_typed_workflow, elaborate_typed_workflow_body
from .route import (
    DEFAULT_LOWERING_ROUTE,
    LoweringRoute,
    normalize_lowering_route,
    validate_wcc_m1_route_supported,
    validate_wcc_m2_route_supported,
    validate_wcc_m3_route_supported,
    validate_wcc_m4_route_supported,
)

__all__ = [
    "DEFAULT_LOWERING_ROUTE",
    "LoweringRoute",
    "WCC_M3_ROUTE_SCHEMA_VERSION",
    "WCC_M1_ROUTE_SCHEMA_VERSION",
    "WCC_M2_ROUTE_SCHEMA_VERSION",
    "WCC_M4_ROUTE_SCHEMA_VERSION",
    "WccAtom",
    "WccBindingValue",
    "WccBody",
    "WccCase",
    "WccCaseArm",
    "WccCall",
    "WccFieldAccessAtom",
    "WccHalt",
    "WccIdentityFactory",
    "WccInject",
    "WccJoin",
    "WccJoinParam",
    "WccJump",
    "WccLet",
    "WccLiteralAtom",
    "WccLoopContinue",
    "WccLoopDone",
    "WccLoopRole",
    "WccNameAtom",
    "WccNodeMetadata",
    "WccOpaqueFrontendValue",
    "WccPhaseTargetAtom",
    "WccPhaseScope",
    "WccPerform",
    "WccProgram",
    "WccRecJoin",
    "WccRecordAtom",
    "WccValue",
    "WccArmScope",
    "WccJoinSite",
    "WccLoopSite",
    "WccScopeAnalysis",
    "analyze_wcc_body",
    "normalize_wcc_body_to_anf",
    "elaborate_typed_workflow",
    "elaborate_typed_workflow_body",
    "normalize_lowering_route",
    "validate_wcc_m1_route_supported",
    "validate_wcc_m2_route_supported",
    "validate_wcc_m3_route_supported",
    "validate_wcc_m4_route_supported",
]
