#!/usr/bin/env python3
from __future__ import annotations

import argparse
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

import yaml


@dataclass(frozen=True)
class PromptRef:
    workflow_path: Path
    step_path: str
    field: str
    authored_path: str
    resolved_path: Path
    exists: bool


def workflow_files(root: Path) -> list[Path]:
    root = root.resolve()
    tracked = git_tracked_workflow_files(root)
    if tracked is not None:
        return tracked
    workflows_root = root / "workflows"
    return sorted(
        path
        for suffix in ("*.yaml", "*.yml")
        for path in workflows_root.rglob(suffix)
        if path.is_file()
    )


def git_tracked_workflow_files(root: Path) -> list[Path] | None:
    result = subprocess.run(
        [
            "git",
            "-C",
            str(root),
            "ls-files",
            "--",
            "workflows/**/*.yaml",
            "workflows/**/*.yml",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return None
    return sorted(root / line for line in result.stdout.splitlines() if line)


def collect_prompt_refs(
    root: Path, workflows: Iterable[Path] | None = None
) -> list[PromptRef]:
    root = root.resolve()
    refs: list[PromptRef] = []
    for workflow in workflows or workflow_files(root):
        workflow = workflow.resolve()
        payload = yaml.safe_load(workflow.read_text(encoding="utf-8")) or {}
        for step_path, step in iter_steps(payload.get("steps", [])):
            refs.extend(refs_for_step(root, workflow, step_path, step))
    return refs


def iter_steps(
    steps: Any, prefix: tuple[str, ...] = ()
) -> Iterable[tuple[str, dict[str, Any]]]:
    if not isinstance(steps, list):
        return
    for index, step in enumerate(steps):
        if not isinstance(step, dict):
            continue
        name = str(step.get("name") or step.get("id") or f"<step {index}>")
        step_prefix = prefix + (name,)
        yield " > ".join(step_prefix), step

        repeat_until = step.get("repeat_until")
        if isinstance(repeat_until, dict):
            yield from iter_steps(repeat_until.get("steps", []), step_prefix)

        for_each = step.get("for_each")
        if isinstance(for_each, dict):
            yield from iter_steps(for_each.get("steps", []), step_prefix)

        then_branch = step.get("then")
        if isinstance(then_branch, dict):
            yield from iter_steps(then_branch.get("steps", []), step_prefix + ("then",))

        else_branch = step.get("else")
        if isinstance(else_branch, dict):
            yield from iter_steps(else_branch.get("steps", []), step_prefix + ("else",))

        match = step.get("match")
        if isinstance(match, dict):
            cases = match.get("cases", {})
            if isinstance(cases, dict):
                for case_name, case_body in cases.items():
                    if isinstance(case_body, dict):
                        yield from iter_steps(
                            case_body.get("steps", []),
                            step_prefix + (f"case {case_name}",),
                        )


def refs_for_step(
    root: Path, workflow: Path, step_path: str, step: dict[str, Any]
) -> list[PromptRef]:
    refs: list[PromptRef] = []
    input_file = step.get("input_file")
    if isinstance(input_file, str):
        refs.append(make_ref(root, workflow, step_path, "input_file", input_file))

    asset_file = step.get("asset_file")
    if isinstance(asset_file, str):
        refs.append(make_ref(root, workflow, step_path, "asset_file", asset_file))

    asset_depends_on = step.get("asset_depends_on")
    if isinstance(asset_depends_on, list):
        for item in asset_depends_on:
            if isinstance(item, str):
                refs.append(
                    make_ref(root, workflow, step_path, "asset_depends_on", item)
                )
    elif isinstance(asset_depends_on, str):
        refs.append(
            make_ref(root, workflow, step_path, "asset_depends_on", asset_depends_on)
        )

    return refs


def make_ref(
    root: Path, workflow: Path, step_path: str, field: str, authored_path: str
) -> PromptRef:
    base = workflow.parent if field in {"asset_file", "asset_depends_on"} else root
    resolved_path = (base / authored_path).resolve()
    return PromptRef(
        workflow_path=workflow,
        step_path=step_path,
        field=field,
        authored_path=authored_path,
        resolved_path=resolved_path,
        exists=resolved_path.is_file(),
    )


def render_markdown(root: Path, refs: Iterable[PromptRef]) -> str:
    lines = [
        "# Workflow Prompt Map",
        "",
        "Generated by `python scripts/workflow_prompt_map.py` from git-tracked workflow YAML files when run inside a git repo.",
        "",
        "Resolution rules:",
        "- `input_file` is repo-root relative.",
        "- `asset_file` is relative to the workflow YAML file's directory.",
        "- `asset_depends_on` is relative to the workflow YAML file's directory.",
        "",
        "| Workflow | Step | Field | Authored Path | Resolved Path | Exists |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for ref in sorted(
        refs,
        key=lambda item: (
            item.workflow_path,
            item.step_path,
            item.field,
            item.authored_path,
        ),
    ):
        lines.append(
            "| "
            f"`{relative_to(root, ref.workflow_path)}` | "
            f"`{ref.step_path}` | "
            f"`{ref.field}` | "
            f"`{ref.authored_path}` | "
            f"`{relative_to(root, ref.resolved_path)}` | "
            f"{'yes' if ref.exists else 'no'} |"
        )
    lines.append("")
    return "\n".join(lines)


def relative_to(root: Path, path: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the workflow-to-prompt map.")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path, default=Path("docs/workflow_prompt_map.md"))
    parser.add_argument(
        "--check", action="store_true", help="Fail if the checked-in map is stale."
    )
    args = parser.parse_args()

    root = args.root.resolve()
    output = args.output if args.output.is_absolute() else root / args.output
    markdown = render_markdown(root, collect_prompt_refs(root))

    if args.check:
        if not output.exists():
            print(f"Missing generated map: {relative_to(root, output)}")
            return 1
        existing = output.read_text(encoding="utf-8")
        if existing != markdown:
            print(f"Stale generated map: {relative_to(root, output)}")
            print("Run: python scripts/workflow_prompt_map.py")
            return 1
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8")
    print(f"Wrote {relative_to(root, output)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
